apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
  namespace: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-backend
  template:
    metadata:
      labels:
        app: library-backend
    spec:
      containers:
        - name: library-backend
          image: wngud1/backend-library:wngud1-backend-library-main-3931b228e083e912025c0509fc73223d1dc67a36
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Asia/Seoul
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: SPRING_DATA_MONGODB_URI
            - name: SPRING_DATA_REDIS_HOST
              value: redis-service.default.svc.cluster.local
            - name: SPRING_DATA_REDIS_PORT
              value: '6379'
          envFrom:
            - secretRef:
                name: spring-config
