apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
  namespace: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-backend
  template:
    metadata:
      labels:
        app: library-backend
    spec:
      containers:
        - name: library-backend
          image: wngud1/backend-library:wngud1/backend-library:main-517d7c89668484d075fd3593936ebed4ee631f10
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Asia/Seoul
          imagePullPolicy: Always
