apiVersion: v1
kind: Service
metadata:
  name: library-backend-svc
  namespace: library
  labels:
    app: library-backend
spec:
  selector:
    app: library-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics              # <-- 관리 포트용 별도 포트
      port: 9090
      targetPort: 9090
  type: ClusterIP
