apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-front
  namespace: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-front
  template:
    metadata:
      labels:
        app: library-front
    spec:
      containers:
        - name: library-front
          image: wngud1/front-library:wngud1-front-library-main-94a8a93251ccb876072ebc78f66d48ef0d0a7e28
          ports:
            - containerPort: 80
          imagePullPolicy: Always
