apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-front
  namespace: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-front
  template:
    metadata:
      labels:
        app: library-front
    spec:
      containers:
        - name: library-front
          image: wngud1/front-library:wngud1/front-library:main-517d7c89668484d075fd3593936ebed4ee631f10
          ports:
            - containerPort: 80
          imagePullPolicy: Always
