apiVersion: v1
kind: Namespace
metadata:
  name: library
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-front
  namespace: library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-front
  template:
    metadata:
      labels:
        app: library-front
    spec:
      containers:
        - name: library-front
          image: wngud1/front-library:0.0.5
          ports:
            - containerPort: 80
          imagePullPolicy:  Always

---